In [1]:
import numpy as np
import sys
import array

In [2]:
## 1. Какие еще существуют коды типов?
array.typecodes # Строка со всеми доступными кодами типов
# 'b', 'B', 'h', 'H', 'i', 'I', 'l', 'L', 'q', 'Q' - int
# 'f', 'd' - float
# 'u' - Unicode character

'bBuhHiIlLqQfd'

In [3]:
## 2. Напишите код, подобный приведенному выше, но с другим типом
a2 = array.array('b', b'hello') # массив с числами типа int, обозначающими символы юникода элементов заданной строки
print(sys.getsizeof(a2))
print(type(a2), a2) 

a3 = array.array('f', [1.4, 3.0, 2.5, 2.7]) # массив чисел с плавающей запятой (тип float)
print(sys.getsizeof(a3))
print(type(a3), a3)  

88
<class 'array.array'> array('b', [104, 101, 108, 108, 111])
96
<class 'array.array'> array('f', [1.399999976158142, 3.0, 2.5, 2.700000047683716])


In [4]:
## 3. Напишите код для создания массива с 5 значениями, располагающимися через равные интервалы в диапазоне от 0 до 1
# Синтаксис: numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None).
print(np.linspace(0, 1, 5))

[0.   0.25 0.5  0.75 1.  ]


In [5]:
## 4. Напишите код для создания массива с 5 равномерно распределенными случайными значениями в диапазоне от 0 до 1
# Синтаксис: numpy.random.uniform(low=0.0, high=1.0, size=None)
print(np.random.uniform(size=5))

[0.47425195 0.44579487 0.22656518 0.3009037  0.21649267]


In [6]:
## 5. Напишите код для создания массива с 5 нормально распределенными случайными значениями с мат. ожиданием = 0 и дисперсией 1
#numpy.random.normal(loc=0, scale=1, size=None), loc - мат.ожидание, scale - дисперсия
print(np.random.normal(loc=0, scale=1, size=5))

[ 0.22858154  1.2981143  -1.30426216 -1.22049311 -0.25371332]


In [7]:
## 6. Напишите код для создания массива с 5 случайнвми целыми числами в от [0, 10)
print(np.random.randint(0, 10, size=5))

[4 0 0 1 9]


In [8]:
## 7. Написать код для создания срезов массива 3 на 4
c = np.random.randint(10, size=(3, 4))
print(c)
## - первые две строки и три столбца
print(c[:2, :3])
## - первые три строки и второй столбец
print(c[::, 1])
## - все строки и столбцы в обратном порядке
print(c[::-1, ::-1])
## - второй столбец
print(c[::, 1])
## - третья строка
print(c[2, ::])

[[9 0 7 9]
 [0 2 3 8]
 [7 7 9 3]]
[[9 0 7]
 [0 2 3]]
[0 2 7]
[[3 9 7 7]
 [8 3 2 0]
 [9 7 0 9]]
[0 2 7]
[7 7 9 3]


In [9]:
## 8. Продемонстрируйте, как сделать срез-копию
a = np.array([1, 2, 3, 4])
b1 = np.copy(a[:3])
print(b1)

b1[0] = 10
print(b1)
print(a)

[1 2 3]
[10  2  3]
[1 2 3 4]


In [10]:
## 9. Продемонстрируйте использование newaxis для получения вектора-столбца и вектора-строки
a = np.arange(1, 10)
a1 = a[:, np.newaxis]
a2 = a[np.newaxis, :]

print(a)
print(a1)
print(a2)

[1 2 3 4 5 6 7 8 9]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
[[1 2 3 4 5 6 7 8 9]]


In [12]:
## 10. Разберитесь, как работает метод dstack
# Используется для стека массивов по глубине (вдоль третьей оси)
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
r1 = np.vstack([x, y])
r2 = np.dstack([r1, r1])
print(r2)

[[[1 1]
  [2 2]
  [3 3]]

 [[4 4]
  [5 5]
  [6 6]]]


In [13]:
## 11. Разберитесь, как работают методы split, vsplit, hsplit, dsplit
# numpy.split() позволяет разделить массив на несколько подмассивов вдоль заданной оси
# Синтаксис: numpy.split(array, indices_or_sections, axis=0)
a = np.arange(10)
print(np.split(a, 5)) # деление на 5 подмассивов по строкам
print(np.split(a, 2)) # деление на 2 подмассива по строкам
print(np.split(a, [3, 5])) # деление на подмассивы с указанием массива, разбивающего исходный массив

b = np.random.randint(10, size=(6, 4))
print(b)
# vsplit разбивает массив на несколько подмассивов по вертикали (строчно)
print(np.vsplit(b, 3))
print(np.vsplit(b, 2))

# hsplit разделяет массив на несколько подмассивов горизонтально (по столбцам)
c = np.random.randint(10, size=(4, 6))
print(np.hsplit(c, 3))
print(np.hsplit(c, 2))

# dsplit разделяет массив на несколько подмассивов вдоль третьей оси (глубины)
d = np.random.randint(10, size=(4, 5, 6))
print(np.dsplit(d, 3))
print(np.dsplit(d, 2))

[array([0, 1]), array([2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]
[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]
[array([0, 1, 2]), array([3, 4]), array([5, 6, 7, 8, 9])]
[[3 2 6 2]
 [6 6 9 1]
 [6 0 7 6]
 [4 9 8 3]
 [7 4 3 2]
 [1 0 3 4]]
[array([[3, 2, 6, 2],
       [6, 6, 9, 1]]), array([[6, 0, 7, 6],
       [4, 9, 8, 3]]), array([[7, 4, 3, 2],
       [1, 0, 3, 4]])]
[array([[3, 2, 6, 2],
       [6, 6, 9, 1],
       [6, 0, 7, 6]]), array([[4, 9, 8, 3],
       [7, 4, 3, 2],
       [1, 0, 3, 4]])]
[array([[9, 9],
       [4, 3],
       [8, 0],
       [5, 4]]), array([[9, 8],
       [9, 0],
       [5, 4],
       [9, 1]]), array([[7, 4],
       [9, 9],
       [2, 6],
       [9, 1]])]
[array([[9, 9, 9],
       [4, 3, 9],
       [8, 0, 5],
       [5, 4, 9]]), array([[8, 7, 4],
       [0, 9, 9],
       [4, 2, 6],
       [1, 9, 1]])]
[array([[[4, 5],
        [8, 0],
        [9, 5],
        [1, 2],
        [3, 8]],

       [[3, 3],
        [3, 1],
        [3, 3],
        [9, 2],
   

In [14]:
## 12. Привести пример использования всех универсальных функций, которые я привел

a = np.array([[1, 2, 3], [2, 3, 4], [3, 4, 5]])
b = np.array([[0, 0, 3], [7, 5, 4], [7, 8, 9]])
# вычитание массивов
print(a - b)

# -
print(-a) 
print(-b)

# деление
print(b / a)
print(b / 2)

# целочисленное деление
print(b // a)
print(b // 2)

# Возведение в степень
print(a ** 3)
print(b ** a)

# остаток от джеления
print(b % 3)
print(b % a)

[[ 1  2  0]
 [-5 -2  0]
 [-4 -4 -4]]
[[-1 -2 -3]
 [-2 -3 -4]
 [-3 -4 -5]]
[[ 0  0 -3]
 [-7 -5 -4]
 [-7 -8 -9]]
[[0.         0.         1.        ]
 [3.5        1.66666667 1.        ]
 [2.33333333 2.         1.8       ]]
[[0.  0.  1.5]
 [3.5 2.5 2. ]
 [3.5 4.  4.5]]
[[0 0 1]
 [3 1 1]
 [2 2 1]]
[[0 0 1]
 [3 2 2]
 [3 4 4]]
[[  1   8  27]
 [  8  27  64]
 [ 27  64 125]]
[[    0     0    27]
 [   49   125   256]
 [  343  4096 59049]]
[[0 0 0]
 [1 2 1]
 [1 2 0]]
[[0 0 0]
 [1 2 0]
 [1 0 4]]
