In [38]:
import numpy as np

In [45]:
## 1. Что надо изменить в последнем примере, чтобы он заработал без ошибок (транслирование)?
# a = np.ones((3, 2))
# b = np.arange(3)

# 2 (3, 2) -> (3, 2) -> (3, 2)
# 1 (3, )  -> (1, 3) -> (3, 3)
# генерируется ошибка, т.к. 2 != 3

In [46]:
# Вариант 1
# изменить размерность массива a
a = np.ones((3, 1))
b = np.arange(3)

# 2 (3, 1) -> (3, 1) -> (3, 3)
# 1 (3,)  -> (1, 3) -> (3, 3)

print(a + b)

[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]


In [47]:
# Вариант 2
# изменить размерность массива b
a = np.ones((3, 2))
b = np.arange(2)

# 2 (3, 2) -> (3, 2) -> (3, 2)
# 1 (2,)  -> (1, 2) -> (3, 2)

print(a + b)

[[1. 2.]
 [1. 2.]
 [1. 2.]]


In [48]:
## 2. Пример для y. Вычислить количество элементов (по обоим размерностям), значения которых больше 3 и меньше 9
y = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]) 
print(np.sum((y > 3) & (y < 9), axis=0))
print(np.sum((y > 3) & (y < 9), axis=1))
print(np.sum((y > 3) & (y < 9)))

[1 1 1 1 1]
[2 3]
5
