In [1]:
import numpy as np
import sys
import array

In [2]:
# Типы данных в Python
# Динамическая типизация - тип данных переменной определяется в ходе выполнения кода

x = 1
print(type(x))  # <class 'int'>
print(sys.getsizeof(x)) # 28 (байт)

x = 'hello'
print(type(x))  # <class 'str'>

x = True
print(type(x)) # <class 'bool'>

l1 = list([])
print(sys.getsizeof(l1)) # 56

l2 = list([1, 2, 3]) # В листе можно хранить элементы разных типов
print(sys.getsizeof(l2))  # 88

<class 'int'>
28
<class 'str'>
<class 'bool'>
56
88


In [3]:
a1 = array.array('i', [1, 2, 3]) # масссив - можно хранить элементы только одного типа
# 'i' - код типа int
print(sys.getsizeof(a1))
print(type(a1))  

92
<class 'array.array'>


In [4]:
a = np.array([1, 2, 3, 4, 5])
print(type(a), a) # <class 'numpy.ndarray'>

<class 'numpy.ndarray'> [1 2 3 4 5]


In [5]:
# "повышающее" приведение типов
a = np.array([1.23, 2, 3, 4, 5])
print(type(a), a)

<class 'numpy.ndarray'> [1.23 2.   3.   4.   5.  ]


In [6]:
# параметр dtype для указания типа
a = np.array([1.23, 2, 3, 4, 5], dtype=int)
print(type(a), a)

<class 'numpy.ndarray'> [1 2 3 4 5]


In [7]:
# создание многомерного массива
a = np.array([range(i, i + 3) for i in [2, 4, 6]])
print(a, type(a))

[[2 3 4]
 [4 5 6]
 [6 7 8]] <class 'numpy.ndarray'>


In [8]:
# массив из нулей
a = np.zeros(10, dtype=int)
print(a, type(a))

[0 0 0 0 0 0 0 0 0 0] <class 'numpy.ndarray'>


In [9]:
# многомерный массив из единиц
a = np.ones((3, 5), dtype=float)
print(a, type(a))

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]] <class 'numpy.ndarray'>


In [10]:
# массив с определенными значениями
print(np.full((4,5), 3.1415))

[[3.1415 3.1415 3.1415 3.1415 3.1415]
 [3.1415 3.1415 3.1415 3.1415 3.1415]
 [3.1415 3.1415 3.1415 3.1415 3.1415]
 [3.1415 3.1415 3.1415 3.1415 3.1415]]


In [11]:
print(np.arange(0, 20, 2))

[ 0  2  4  6  8 10 12 14 16 18]


In [12]:
# получение единичной матрицы определенного размера
print(np.eye(4))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [13]:
# МАССИВЫ

In [14]:
np.random.seed(1) # устанавливает начальное значение

In [15]:
x1 = np.random.randint(10, size=3)
x2 = np.random.randint(10, size=(3, 2))
x3 = np.random.randint(10, size=(3, 2, 1))

# print(x1)
# print(x2)
# print(x3)

# Число размерностей массива, размер каждой размерности и общий размер массива
print(x1.ndim, x1.shape, x1.size)
print(x2.ndim, x2.shape, x2.size)
print(x3.ndim, x3.shape, x3.size)

1 (3,) 3
2 (3, 2) 6
3 (3, 2, 1) 6


In [16]:
# Индекс (с 0)
a = np.array([1, 2, 3, 4, 5])
print(a[0])
print(a[-2])
a[1] = 20
print(a)

1
4
[ 1 20  3  4  5]


In [17]:
# доступ по индексам в многомерных массивах
a = np.array([[1, 2], [3, 4]])
print(a)
print(a[0, 0])
print(a[-1, -1])
a[1, 0] = 100
print(a)

[[1 2]
 [3 4]]
1
4
[[  1   2]
 [100   4]]


In [18]:
a = np.array([1, 2, 3, 4])
b = np.array([1.0, 2, 3, 4])

print(a)
print(b)

a[0] = 10
print(a)

a[0] = 10.123
print(a)

[1 2 3 4]
[1. 2. 3. 4.]
[10  2  3  4]
[10  2  3  4]


In [19]:
## Срез - подмассив [start:finish:step], по умолчанию - [0:shape:1]
a = np.array([1, 2, 3, 4, 5, 6])
print(a[:3])
print(a[3:])
print(a[1:5])
print(a[1:-1])
print(a[1::2])
print(a[::1])
print(a[::-1])

[1 2 3]
[4 5 6]
[2 3 4 5]
[2 3 4 5]
[2 4 6]
[1 2 3 4 5 6]
[6 5 4 3 2 1]


In [20]:
# срезы - не копии, а ссылки на части массива
b = a[:3]
print(b)

b[0] = 100
print(a)

[1 2 3]
[100   2   3   4   5   6]


In [21]:
a = np.arange(1, 13)
print(a)
# меняем размерность массива
print(a.reshape(2, 6))
print(a.reshape(3, 4))

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [22]:
x = np.array([1, 2, 3])
y = np.array([4, 5])
z = np.array([6])

# объединение массивов
print(np.concatenate([x, y, z]))

x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

# вертикальное склеивание
r1 = np.vstack([x, y])
print(r1)

# горизонтальное склеивание
print(np.hstack([r1, r1]))

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]


In [23]:
### Вычисления с массивами
# векторизированные операция - применяется независимо к каждому элементу массива
X = np.arange(10)
print(x)
print(x * 2 + 1)

# Универсальные функции
print(np.add(np.multiply(x, 2), 1))

# - - / // ** %

[1 2 3]
[3 5 7]
[3 5 7]


In [24]:
## np.abs, sin/cos/tan, exp, log
x = np.arange(5)
y = np.zeros(10)
print(np.multiply(x, 10, out=y[::2]))
print(y)

[ 0. 10. 20. 30. 40.]
[ 0.  0. 10.  0. 20.  0. 30.  0. 40.  0.]


In [25]:
x = np.arange(1, 5)
print(x)

print(np.add.reduce(x))
print(np.add.accumulate(x))

[1 2 3 4]
10
[ 1  3  6 10]


In [26]:
x = np.arange(1, 10)
print(np.add.outer(x, x))
print(np.multiply.outer(x, x))

[[ 2  3  4  5  6  7  8  9 10]
 [ 3  4  5  6  7  8  9 10 11]
 [ 4  5  6  7  8  9 10 11 12]
 [ 5  6  7  8  9 10 11 12 13]
 [ 6  7  8  9 10 11 12 13 14]
 [ 7  8  9 10 11 12 13 14 15]
 [ 8  9 10 11 12 13 14 15 16]
 [ 9 10 11 12 13 14 15 16 17]
 [10 11 12 13 14 15 16 17 18]]
[[ 1  2  3  4  5  6  7  8  9]
 [ 2  4  6  8 10 12 14 16 18]
 [ 3  6  9 12 15 18 21 24 27]
 [ 4  8 12 16 20 24 28 32 36]
 [ 5 10 15 20 25 30 35 40 45]
 [ 6 12 18 24 30 36 42 48 54]
 [ 7 14 21 28 35 42 49 56 63]
 [ 8 16 24 32 40 48 56 64 72]
 [ 9 18 27 36 45 54 63 72 81]]
